/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.CRUD_Autores;
import Controlador.CRUD_ObrasArte;
import Controlador.CRUD_TipoObras;
import Modelo.Autores;
import Modelo.ObrasArte;
import Modelo.Tipo_Obras;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reformador
 */
public class frmObrasArte extends javax.swing.JInternalFrame {
    //Instancia a CRUD tipos de Obra
    CRUD_TipoObras crudto=new CRUD_TipoObras();
    //Instancia a CRUD Autores
    CRUD_Autores crudau=new CRUD_Autores();
    //Instancia a CRUD Obras Arte
    CRUD_ObrasArte crud=new CRUD_ObrasArte();
    
    //Método local para recibir el arraylist
    private void llenar_tabla(String buscar){
        ArrayList<ObrasArte> datos=crud.leer(buscar);
        //Objeto de tipo tabla para manipular los datos
        DefaultTableModel tabla=new DefaultTableModel();
        tabla.setColumnCount(0);
        tabla.addColumn("Código");
        tabla.addColumn("Título");
        tabla.addColumn("F. Creación");
        tabla.addColumn("F. Ingreso");
        tabla.addColumn("Autor");
        //Determinar cantidad de filas de la tabla
        tabla.setNumRows(datos.size());
        this.jLabel4.setText("Cantidad de Registros: "+datos.size());
        //Crear una instancia de clase Obras Arte
        ObrasArte o;
        //Cargar los datos a las filas del modelo
        for (int i = 0; i < datos.size(); i++) {
            o=(ObrasArte)datos.get(i);
            tabla.setValueAt(o.getOa_cod(), i, 0);
            tabla.setValueAt(o.getOa_titulo(), i, 1);
            tabla.setValueAt(o.getOa_fcrea(), i, 2);
            tabla.setValueAt(o.getOa_fing(), i, 3);
            tabla.setValueAt(o.getAut_nom(), i, 4);
        }
        //Reemplazar la tabla por el modelo
        jTable1.setModel(tabla);
    }
    //Método local para limpiar cajas
    private void limpiar(String mensaje){
        titulo.setText("");
        fechac.setText("");
        fechai.setText("");
        titulo.grabFocus();
        llenar_autores();
        llenar_tipoobra();
        JOptionPane.showMessageDialog(this, mensaje,"Información",
                JOptionPane.INFORMATION_MESSAGE);
        //Llenar la tabla de datos cada vez que se modifica la BD
        llenar_tabla("");
    }
    
    
    //Método para cargar Lista desplegable de Tipos de Obra
    public void llenar_autores(){
        try{
            ArrayList<Autores> datos=crudau.leer("");
            //OBjeto de tipo JCOMBOBox
            DefaultComboBoxModel modelo=new DefaultComboBoxModel();
            //Recorrer el ArrayList
            for(Autores au:datos){
                au=new Autores(au.getAut_cod(), au.getAut_nom());
                modelo.addElement(au);
            }
            //Lllenar la vista con el objeto
            autor.setModel(modelo);
        }catch(Exception e){
            System.out.println("Error: "+e);
        }
    }
    
    //Método para cargar Lista desplegable de Tipos de Obra
    public void llenar_tipoobra(){
        try{
            ArrayList<Tipo_Obras> datos=crudto.leer("");
            //OBjeto de tipo JCOMBOBox
            DefaultComboBoxModel modelo=new DefaultComboBoxModel();
            //Recorrer el ArrayList
            for(Tipo_Obras to:datos){
                to=new Tipo_Obras(to.getTo_cod(), to.getTo_des());
                modelo.addElement(to);
            }
            //Lllenar la vista con el objeto
            tipoobra.setModel(modelo);
        }catch(Exception e){
            System.out.println("Error: "+e);
        }
    }
    
    /**
     * Creates new form frmObrasArte
     */
    public frmObrasArte() {
        initComponents();
        //Llenar lista de tipos de Obra
        llenar_tipoobra();
        //Llenar lista de autores
        llenar_autores();
        //Lllenar tabla con Obras de Arte
        llenar_tabla("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        bcancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        bgrabar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        bmodificar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        beliminar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        buscador = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fechai = new javax.swing.JFormattedTextField();
        autor = new javax.swing.JComboBox();
        tipoobra = new javax.swing.JComboBox();
        fechac = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Obras de Arte...");

        jToolBar1.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        bcancelar.setBackground(new java.awt.Color(0, 0, 0));
        bcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancel_32.png"))); // NOI18N
        bcancelar.setToolTipText("Nuevo Registro.");
        bcancelar.setEnabled(false);
        bcancelar.setFocusable(false);
        bcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bcancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(bcancelar);
        jToolBar1.add(jSeparator1);

        bgrabar.setBackground(new java.awt.Color(0, 0, 0));
        bgrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save_32.png"))); // NOI18N
        bgrabar.setToolTipText("Grabar Registro.");
        bgrabar.setFocusable(false);
        bgrabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bgrabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bgrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgrabarActionPerformed(evt);
            }
        });
        jToolBar1.add(bgrabar);
        jToolBar1.add(jSeparator2);

        bmodificar.setBackground(new java.awt.Color(0, 0, 0));
        bmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update_32.png"))); // NOI18N
        bmodificar.setToolTipText("Editar Registro.");
        bmodificar.setEnabled(false);
        bmodificar.setFocusable(false);
        bmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodificarActionPerformed(evt);
            }
        });
        jToolBar1.add(bmodificar);
        jToolBar1.add(jSeparator3);

        beliminar.setBackground(new java.awt.Color(0, 0, 0));
        beliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_32.png"))); // NOI18N
        beliminar.setToolTipText("Eliminar Registro.");
        beliminar.setEnabled(false);
        beliminar.setFocusable(false);
        beliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        beliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(beliminar);
        jToolBar1.add(jSeparator4);

        buscador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscador.setForeground(new java.awt.Color(51, 51, 51));
        buscador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscadorKeyTyped(evt);
            }
        });
        jToolBar1.add(buscador);
        jToolBar1.add(jSeparator5);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista Tipos de Obra...", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar2.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad de Registros: ?");
        jToolBar2.add(jLabel4);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Obra de Arte...", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Título: ");

        jLabel2.setText("Año Creación: ");

        jLabel3.setText("Fecha Ingreso: ");

        jLabel5.setText("Autor: ");

        jLabel6.setText("Tipo Obra: ");

        try {
            fechai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        autor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tipoobra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(autor, 0, 162, Short.MAX_VALUE)
                            .addComponent(fechac))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tipoobra, 0, 165, Short.MAX_VALUE)
                            .addComponent(fechai)))
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(fechai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoobra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelarActionPerformed
        /*titulo.setText("");

        titulo.grabFocus();
        //Desactivar botones
        bcancelar.setEnabled(false);
        bmodificar.setEnabled(false);
        beliminar.setEnabled(false);
        bgrabar.setEnabled(true);*/
    }//GEN-LAST:event_bcancelarActionPerformed

    private void bgrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgrabarActionPerformed
        //Rescatar codigo autor
        Autores a=(Autores)autor.getSelectedItem();
        //Rescatar código tipo Obra
        Tipo_Obras to=(Tipo_Obras)tipoobra.getSelectedItem();
        
        if(crud.insertar(titulo.getText(),fechac.getText(),fechai.getText(),a.getAut_cod(),to.getTo_cod())){
            limpiar("Registro creado Correctamente");
        }else{
            JOptionPane.showMessageDialog(this,
                "Error al Crear Registro");
        }
    }//GEN-LAST:event_bgrabarActionPerformed

    private void bmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodificarActionPerformed
   /*     if(crud.modificar(codigo,titulo.getText())){
            limpiar("Registro Modificado Correctamente");
        }else{
            JOptionPane.showMessageDialog(this,
                "Error al Modificar Registro");
        }
        //Desactivar botones
        bcancelar.setEnabled(false);
        bmodificar.setEnabled(false);
        beliminar.setEnabled(false);
        bgrabar.setEnabled(true);*/
    }//GEN-LAST:event_bmodificarActionPerformed

    private void beliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliminarActionPerformed
        /*if(crud.eliminar(codigo)){
            limpiar("Registro Eliminado Correctamente");
        }else{
            JOptionPane.showMessageDialog(this,
                "Error al Eliminar Registro");
        }
        //Desactivar botones
        bcancelar.setEnabled(false);
        bmodificar.setEnabled(false);
        beliminar.setEnabled(false);
        bgrabar.setEnabled(true);*/
    }//GEN-LAST:event_beliminarActionPerformed

    private void buscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscadorKeyTyped
        //llenar_tabla(buscador.getText());
    }//GEN-LAST:event_buscadorKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //Determinar fila en la cual presiona el mouse el usuario
       /* fila=jTable1.rowAtPoint(evt.getPoint());
        if (fila>-1) {
            codigo=Integer.parseInt(String.valueOf(jTable1.getValueAt(fila, 0)));
            titulo.setText(String.valueOf(jTable1.getValueAt(fila, 1)));

            //Desactivar botones
            bcancelar.setEnabled(true);
            bmodificar.setEnabled(true);
            beliminar.setEnabled(true);
            bgrabar.setEnabled(false);
        }*/
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox autor;
    private javax.swing.JButton bcancelar;
    private javax.swing.JButton beliminar;
    private javax.swing.JButton bgrabar;
    private javax.swing.JButton bmodificar;
    private javax.swing.JTextField buscador;
    private javax.swing.JTextField fechac;
    private javax.swing.JFormattedTextField fechai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JComboBox tipoobra;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
