package Vista;

import Controlador.CRUD_TipoObras;
import Modelo.Tipo_Obras;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmTipoObras extends javax.swing.JInternalFrame {
 //Variable para almacenar el click del mouse en la tabla
    int fila=-1;
    //Variable para almacenar codigo de Tipo de Obra
    int codigo;
    //Instancia a CRUD_TiposObra
    CRUD_TipoObras crud=new CRUD_TipoObras();
    
    //Método local para recibir el arraylist
    private void llenar_tabla(String buscar){
        ArrayList<Tipo_Obras> datos=crud.leer(buscar);
        //Objeto de tipo tabla para manipular los datos
        DefaultTableModel tabla=new DefaultTableModel();
        tabla.setColumnCount(0);
        tabla.addColumn("Código");
        tabla.addColumn("Tipo de Obra");
        //Determinar cantidad de filas de la tabla
        tabla.setNumRows(datos.size());
        this.jLabel4.setText("Cantidad de Registros: "+datos.size());
        //Crear una instancia de clase TiposObra
        Tipo_Obras u;
        //Cargar los datos a las filas del modelo
        for (int i = 0; i < datos.size(); i++) {
            u=(Tipo_Obras)datos.get(i);
            tabla.setValueAt(u.getTo_cod(), i, 0);
            tabla.setValueAt(u.getTo_des(), i, 1);
        }
        //Reemplazar la tabla por el modelo
        jTable1.setModel(tabla);
    }
    //Método local para limpiar cajas
    private void limpiar(String mensaje){
        nombre.setText("");
        nombre.grabFocus();
        JOptionPane.showMessageDialog(this, mensaje,"Información",
                JOptionPane.INFORMATION_MESSAGE);
        //Llenar la tabla de datos cada vez que se modifica la BD
        llenar_tabla("");
    }
    
    public frmTipoObras() {
        initComponents();
        llenar_tabla("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        bcancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        bgrabar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        bmodificar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        beliminar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        buscador = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Tipos de Obra");

        jToolBar1.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        bcancelar.setBackground(new java.awt.Color(0, 0, 0));
        bcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancel_32.png"))); // NOI18N
        bcancelar.setToolTipText("Nuevo Registro.");
        bcancelar.setEnabled(false);
        bcancelar.setFocusable(false);
        bcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bcancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(bcancelar);
        jToolBar1.add(jSeparator1);

        bgrabar.setBackground(new java.awt.Color(0, 0, 0));
        bgrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save_32.png"))); // NOI18N
        bgrabar.setToolTipText("Grabar Registro.");
        bgrabar.setFocusable(false);
        bgrabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bgrabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bgrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgrabarActionPerformed(evt);
            }
        });
        jToolBar1.add(bgrabar);
        jToolBar1.add(jSeparator2);

        bmodificar.setBackground(new java.awt.Color(0, 0, 0));
        bmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update_32.png"))); // NOI18N
        bmodificar.setToolTipText("Editar Registro.");
        bmodificar.setEnabled(false);
        bmodificar.setFocusable(false);
        bmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmodificarActionPerformed(evt);
            }
        });
        jToolBar1.add(bmodificar);
        jToolBar1.add(jSeparator3);

        beliminar.setBackground(new java.awt.Color(0, 0, 0));
        beliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_32.png"))); // NOI18N
        beliminar.setToolTipText("Eliminar Registro.");
        beliminar.setEnabled(false);
        beliminar.setFocusable(false);
        beliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        beliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(beliminar);
        jToolBar1.add(jSeparator4);

        buscador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscador.setForeground(new java.awt.Color(51, 51, 51));
        buscador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscadorKeyTyped(evt);
            }
        });
        jToolBar1.add(buscador);
        jToolBar1.add(jSeparator5);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipos de Obra...", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Nombre: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista Tipos de Obra...", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jToolBar2.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad de Registros: ?");
        jToolBar2.add(jLabel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelarActionPerformed
        nombre.setText("");
        
        nombre.grabFocus();
        //Desactivar botones
        bcancelar.setEnabled(false);
        bmodificar.setEnabled(false);
        beliminar.setEnabled(false);
        bgrabar.setEnabled(true);
    }//GEN-LAST:event_bcancelarActionPerformed

    private void bgrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgrabarActionPerformed
        if(crud.insertar(nombre.getText())){
            limpiar("Registro creado Correctamente");
        }else{
            JOptionPane.showMessageDialog(this, 
                    "Error al Crear Registro");
        }
    }//GEN-LAST:event_bgrabarActionPerformed

    private void bmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmodificarActionPerformed
        if(crud.modificar(codigo,nombre.getText())){
            limpiar("Registro Modificado Correctamente");
        }else{
            JOptionPane.showMessageDialog(this, 
                    "Error al Modificar Registro");
        }
        //Desactivar botones
        bcancelar.setEnabled(false);
        bmodificar.setEnabled(false);
        beliminar.setEnabled(false);
        bgrabar.setEnabled(true);
    }//GEN-LAST:event_bmodificarActionPerformed

    private void beliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliminarActionPerformed
       if(crud.eliminar(codigo)){
            limpiar("Registro Eliminado Correctamente");
        }else{
            JOptionPane.showMessageDialog(this, 
                    "Error al Eliminar Registro");
        }
        //Desactivar botones
        bcancelar.setEnabled(false);
        bmodificar.setEnabled(false);
        beliminar.setEnabled(false);
        bgrabar.setEnabled(true);
    }//GEN-LAST:event_beliminarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //Determinar fila en la cual presiona el mouse el usuario
        fila=jTable1.rowAtPoint(evt.getPoint());
        if (fila>-1) {
            codigo=Integer.parseInt(String.valueOf(jTable1.getValueAt(fila, 0)));
            nombre.setText(String.valueOf(jTable1.getValueAt(fila, 1)));
           
            //Desactivar botones
            bcancelar.setEnabled(true);
            bmodificar.setEnabled(true);
            beliminar.setEnabled(true);
            bgrabar.setEnabled(false);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void buscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscadorKeyTyped
        llenar_tabla(buscador.getText());
    }//GEN-LAST:event_buscadorKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcancelar;
    private javax.swing.JButton beliminar;
    private javax.swing.JButton bgrabar;
    private javax.swing.JButton bmodificar;
    private javax.swing.JTextField buscador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
